// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zczgznejrqmgilzuidbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjemd6bmVqcnFtZ2lsenVpZGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTk0MTcsImV4cCI6MjA2MDU3NTQxN30.x9EgEG0l-vrfPCqccMirCOfJKajeFozkKTfWGBG_0RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);